---
server:
    install: '1'
    packages: [vim, htop]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant/project
    servername: myApp.vb
mysql:
    install: '1'
    root_password: '1'
    database: magento
    user: magento_user
    password: 1
    dump: ''
redis:
    install: '1'
    port: '6379'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-dev, php-pear, php5-curl]
phpmyadmin:
    install: '1'

